### ISSUE TITLE
Abnormal high-frequent viewchange message after receiving messages generated by fuzzer

### ISSUE THREAD

**Issue by sardChen** [SmartBFT-Go/fabric#274]
1. Set up a ten-node(one fuzzer node, 9 normal nodes)  network using smartbft based on the first-network in  [https://github.com/SmartBFT-Go/fabric-samples](https://github.com/SmartBFT-Go/fabric-samples)
2. Fuzzer node sends some fuzzed messages (preprepare, prepare and commit messages are mutated based  on a channel creation configtx, other messages such as heartbeat, StateTransfer are mutated randomly),  then we can close the fuzzer node.
3. After receiving the messages generated by fuzzer node, all normal nodes begin sending and receiving massive viewchange and StateTransfer messages continuously and high-frequently, and other messages can be hardly dealt with.
4. This situation can be reproduced all the time, which makes me hard to fuzz deep logics in smartbft.

All messages sending and receiving by nodes are print out, which can be found in [https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog](https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog).
Orderer1 is the fuzzer node, the others are normal smartbft nodes.

**Comment by yacovm** [comment]
Thanks a lot for the work and the logs. I will check it this week.

Can you please put a link to your fuzzer code that mutates the messages? I will run it locally.

**Comment by yacovm** [comment]
Also can you please re-run your experiment with DEBUG logging level?

**Comment by sardChen** [comment]
> Also can you please re-run your experiment with DEBUG logging level?

Here are the logs with DEBUG logging level. [https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_abnormal_viewchange](https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_abnormal_viewchange)



> Thanks a lot for the work and the logs. I will check it this week.
> 
> Can you please put a link to your fuzzer code that mutates the messages? I will run it locally.

Many thanks for your response.
For the fuzzer code, I will clean up my code and upload it later. I will let you know once I finish it.

**Comment by sardChen** [comment]
> Thanks a lot for the work and the logs. I will check it this week.
> 
> Can you please put a link to your fuzzer code that mutates the messages? I will run it locally.

**Comment by sardChen** [comment]
> > Also can you please re-run your experiment with DEBUG logging level?
> 
> Here are the logs with DEBUG logging level. https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_abnormal_viewchange
> 
> > Thanks a lot for the work and the logs. I will check it this week.
> > Can you please put a link to your fuzzer code that mutates the messages? I will run it locally.
> 
> Many thanks for your response.
> For the fuzzer code, I will clean up my code and upload it later. I will let you know once I finish it.

The fuzzer code  can be found here: [https://github.com/sardChen/SmartBFT-Fuzz](https://github.com/sardChen/SmartBFT-Fuzz)

**Comment by yacovm** [comment]
Thanks I'll check it this week

**Comment by yacovm** [comment]
Hey @sardChen , I tested this locally in this [test](https://github.com/yacovm/consensus/blob/fuzz/test/basic_test.go#L30-L133), and I think that we don't have a bug, and that maybe you by accident had the output of all nodes get fuzzed, and not only a third of them:

In your code, you fuzz all the time. 
https://github.com/sardChen/SmartBFT-Fuzz/blob/main/smartbft/egress.go#L55-L65
How did you make only some of the nodes be fuzzed and some not? Did you use different docker images for different nodes? 3 nodes with the custom docker image and the rest of the nodes with regular smartbft images?

**Comment by sardChen** [comment]
> Hey @sardChen , I tested this locally in this [test](https://github.com/yacovm/consensus/blob/fuzz/test/basic_test.go#L30-L133), and I think that we don't have a bug, and that maybe you by accident had the output of all nodes get fuzzed, and not only a third of them:
> 
> In your code, you fuzz all the time.
> https://github.com/sardChen/SmartBFT-Fuzz/blob/main/smartbft/egress.go#L55-L65
> How did you make only some of the nodes be fuzzed and some not? Did you use different docker images for different nodes? 3 nodes with the custom docker image and the rest of the nodes with regular smartbft images?

All of ten nodes are using the same custom docker images, but I also have changed the code in view.go and controller.go that only one of the nodes will call sendConsensusFuzz and send fuzzed messages, the other nodes run with original logic. As you can see in [these logs](https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_abnormal_viewchange), only log_orderer1 (the fuzzer nodes) has sent Fuzzed consensus.

**Comment by yacovm** [comment]
But in the [egress.go](https://github.com/sardChen/SmartBFT-Fuzz/blob/main/smartbft/egress.go#L56) code, you fuzz the message regardless of which node you are. It doesn't matter what you do in the view.go or controller.go, if you still fuzz all messages for all nodes in the fabric side code.

The debug logs actually look fine to me. What is the problem you see in the debug logs?

In the non-debug logs I think that all nodes have fuzzing activated.

**Comment by sardChen** [comment]
> But in the [egress.go](https://github.com/sardChen/SmartBFT-Fuzz/blob/main/smartbft/egress.go#L56) code, you fuzz the message regardless of which node you are. It doesn't matter what you do in the view.go or controller.go, if you still fuzz all messages for all nodes in the fabric side code.
> 
> The debug logs actually look fine to me. What is the problem you see in the debug logs?
> 
> In the non-debug logs I think that all nodes have fuzzing activated.

Currently, in controller.go, only the leader node (I have added if condition: v.SelfID == v.LeaderID) will call sendConsensusFuzz in egress.go, the other nodes still call sendConsensus. After leader node sending the first several messages, I will stop it by docker stop command, and the [debug logs](https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_abnormal_viewchange) are produced in this way. Take [order2](https://raw.githubusercontent.com/sardChen/SmartBFT-Fuzz/main/ErrorLog_debug_abnormal_viewchange/log_orderer2) for example, there is at least one viewchange message a second ([orderer.consensus.smartbft] OnConsensus -> INFO 7b8[0m Receive consensus, type is ViewChange 		content is view_change:<next_view:1 >), and all the contents are the same. Is that normal?

**Comment by yacovm** [comment]
> Currently, in controller.go, only the leader node (I have added if condition: v.SelfID == v.LeaderID) will call sendConsensusFuzz in egress.go


But this means you are fuzzing all nodes, not only a specific node. 
If a leader node sends something that doesn't make sense to the follower node, the follower node will suspect that leader and will start a view change. Eventually, if enough follower nodes will suspect the leader, a view change occurs, and a new leader is selected. That new leader, will also fuzz its messages, according to your code `v.SelfID == v.LeaderID`, and this will happen again and again. 
What you need to do, is to make a condition that only fuzzes a specific node, for example, node 1: `v.SelfID == 1` because otherwise your code is just making every node byzantine, once it becomes a leader.

**Comment by sardChen** [comment]
> > Currently, in controller.go, only the leader node (I have added if condition: v.SelfID == v.LeaderID) will call sendConsensusFuzz in egress.go
> 
> But this means you are fuzzing all nodes, not only a specific node.
> If a leader node sends something that doesn't make sense to the follower node, the follower node will suspect that leader and will start a view change. Eventually, if enough follower nodes will suspect the leader, a view change occurs, and a new leader is selected. That new leader, will also fuzz its messages, according to your code `v.SelfID == v.LeaderID`, and this will happen again and again.
> What you need to do, is to make a condition that only fuzzes a specific node, for example, node 1: `v.SelfID == 1` because otherwise your code is just making every node byzantine, once it becomes a leader.

I understand what you mean.
However, the question is that after the follower nodes suspect the leader (fuzzer node) and start a view change, there is no new leader selected. That's why only [orderer1_log](https://github.com/sardChen/SmartBFT-Fuzz/blob/main/ErrorLog_debug_abnormal_viewchange/log_orderer1) has sent the fuzzed message, the others have not.
Even after I stop the orderer1 manually, the new leader is still not selected, that's why the rest of the nine nodes continually send viewchange to each other, as you can see in the debug [logs.](https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_abnormal_viewchange)

**Comment by yacovm** [comment]
I think that only orderer3 and orderer9 are trying to do a view change, and this is not enough for the view change to succeed. The other nodes didn't receive a pre-prepare from orderer1, probably it was too soon and the communication wasn't initialized yet. 

If you want to make the nodes detect that orderer1 is fuzzed, you need to wait a bit until the communication is stable after the system starts, and only then, send the transaction. 

If you stop the leader node manually then after enough time, the nodes will start doing a view change and elect a new leader.

**Comment by sardChen** [comment]
> I think that only orderer3 and orderer9 are trying to do a view change, and this is not enough for the view change to succeed. The other nodes didn't receive a pre-prepare from orderer1, probably it was too soon and the communication wasn't initialized yet.
> 
> If you want to make the nodes detect that orderer1 is fuzzed, you need to wait a bit until the communication is stable after the system starts, and only then, send the transaction.
> 
> If you stop the leader node manually then after enough time, the nodes will start doing a view change and elect a new leader.

2~3 minutes after I stop the leader node (fuzzer node) manually, the nodes start doing a view change and elect a new leader, and everything goes well.
However, I did another experiment. I changed the if condition to **v.SelfID == 1**, so that there is only one fuzzer node in these ten orderer nodes. According to the new [logs,](https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_oneFuzzer) I find that orderer3 and orderer8 continually _startViewChange_ and send view_change requests for a long time (So far, it's been a couple of hours, and _startViewChange_ happens every 20 seconds), the other nodes behaved normally.
 In this case, fuzzer node randomly sent different fuzzed preprepare messages and fuzzed prepare messages to the other normal orderers, some may receive, some may not, and then fuzzer nodes stopped sending fuzzed messages.
I wonder if this situation is normal?
The details can be found in these new [logs.](https://github.com/sardChen/SmartBFT-Fuzz/tree/main/ErrorLog_debug_oneFuzzer)

**Comment by yacovm** [comment]
Yes, this is normal and by design. Let me explain why. 

A view change is a protocol that is designed to overthrow a faulty leader in case it either crashed or is suspected to be Byzantine.

The assumption in BFT protocols is that given `n` nodes in the system, less than a third of the nodes are faulty, or in other words - up to `f=(n-1)/3` are faulty. If `n=10` then `f=3`. 

If you have up to `f` nodes that either crashed or are Byzantine, then the BFT protocol needs a certain of nodes to agree on the steps of the protocol. The minimum number of nodes that are required to agree, is defined to be the minimum size of a subset of all nodes, such that each two such subsets, intersect with at least one honest node. 

Such a subset of nodes is called a quorum, and every two quorums, by definition, must intersect at `f+1` nodes, because it means that at least one node out of the `f+1` nodes common to both subsets, is honest.

With simple algebra we see that the quorum size needs to be 2f+1, because if we take two subsets each of size `2f+1` and compute the smallest possible intersection of them by subtracting `n`, we get:  `(2f+1)*2 - n = 4f+2 - (3n+1) = f+1`.

When `n=10, f=3` the quorum size is `7`, so it means that we need `7` nodes to suspect the leader before a view change occurs. 

In your example, only nodes 3 and 8 suspect the leader and start a view change, and it's fine, because 2 nodes is less than the minimum required nodes for the view change to finish successfully. 

Now, imagine what would happen, if it would only take two nodes to make a view change. Since `f=3`, then you can have two malicious nodes that can always start a view change, claiming the leader is misbehaving. Then, these two nodes can cause the leader to change, and then they can do another view change, and another, and another, and the system would not have time to finish any consensus round and agree on blocks because it would be busy with constantly changing leaders!

**Comment by sardChen** [comment]
> Yes, this is normal and by design. Let me explain why.
> 
> A view change is a protocol that is designed to overthrow a faulty leader in case it either crashed or is suspected to be Byzantine.
> 
> The assumption in BFT protocols is that given `n` nodes in the system, less than a third of the nodes are faulty, or in other words - up to `f=(n-1)/3` are faulty. If `n=10` then `f=3`.
> 
> If you have up to `f` nodes that either crashed or are Byzantine, then the BFT protocol needs a certain of nodes to agree on the steps of the protocol. The minimum number of nodes that are required to agree, is defined to be the minimum size of a subset of all nodes, such that each two such subsets, intersect with at least one honest node.
> 
> Such a subset of nodes is called a quorum, and every two quorums, by definition, must intersect at `f+1` nodes, because it means that at least one node out of the `f+1` nodes common to both subsets, is honest.
> 
> With simple algebra we see that the quorum size needs to be 2f+1, because if we take two subsets each of size `2f+1` and compute the smallest possible intersection of them by subtracting `n`, we get: `(2f+1)*2 - n = 4f+2 - (3n+1) = f+1`.
> 
> When `n=10, f=3` the quorum size is `7`, so it means that we need `7` nodes to suspect the leader before a view change occurs.
> 
> In your example, only nodes 3 and 8 suspect the leader and start a view change, and it's fine, because 2 nodes is less than the minimum required nodes for the view change to finish successfully.
> 
> Now, imagine what would happen, if it would only take two nodes to make a view change. Since `f=3`, then you can have two malicious nodes that can always start a view change, claiming the leader is misbehaving. Then, these two nodes can cause the leader to change, and then they can do another view change, and another, and another, and the system would not have time to finish any consensus round and agree on blocks because it would be busy with constantly changing leaders!

I understand what you mean.
But my question is that as a fuzzer node, it has already sent different messages to different nodes. After conducting such malicious behavior, why there are only nodes 3 and 8 suspecting the leader, when the other normal nodes can start suspect it and finish the view change process?
On the other hand, after trying _startViewChange_ so many times, it can be much better if there are some mechanisms to either stop trying or letting other normal nodes believe you with some proof, rather than keep sending so many messages all the time. Especially when the numbers of nodes in the network become much larger, so many repeated view_change messages can be a mess.

**Comment by yacovm** [comment]
> But my question is that as a fuzzer node, it has already sent different messages to different nodes. After conducting such malicious behavior, why there are only nodes 3 and 8 suspecting the leader, when the other normal nodes can start suspect it and finish the view change process?

Because the other nodes haven't received the pre-prepare message from some reason. Probably because you needed more time for the network to stabilize after the nodes started. Maybe if you try to send several transactions one after another, it will get to everyone?

> On the other hand, after trying startViewChange so many times, it can be much better if there are some mechanisms to either stop trying or letting other normal nodes believe you with some proof, rather than keep sending so many messages all the time. Especially when the numbers of nodes in the network become much larger, so many repeated view_change messages can be a mess.

But you do a view change if you suspect the node. A malicious node can always make only some of the honest nodes suspect him, but not too much of them because then they will overthrow him from being a leader. 
If the pre-prepare was signed, then it would be possible to prove to nodes that the leader was misbehaving, but, it's not signed for performance reasons. 

Ultimately, a malicious leader can always just not send any message to a minority of the honest nodes, and they can replicate the blocks later from the rest of the honest nodes.

As for the repeated view change messages - the idea of repeating them, is that sometimes the network itself can be down, and you don't get heartbeats from the leader so you (as a follower node) want to start a view change, but the network can still be down for a long time. So you repeatedly send view change messages once in a while, until at some time the network will heal.

Don't forget that the view change message is very cheap, it only has a single integer (view number) and that's it.
