### ISSUE TITLE
Expose the BFT library configuration to the orderer configuration

### ISSUE THREAD

**Issue by yacovm** [SmartBFT-Go/fabric#86]

**Comment by tock-ibm** [comment]
The consensus library exposes the following configuration:

var DefaultConfig = Configuration{
    RequestBatchMaxCount:      100,
    RequestBatchMaxBytes:      10 * 1024 * 1024,
    RequestBatchMaxInterval:   50 * time.Millisecond,
    IncomingMessageBufferSize: 200,
    RequestPoolSize:           400,
    RequestTimeout:            2 * time.Second,
    RequestLeaderFwdTimeout:   20 * time.Second,
    RequestAutoRemoveTimeout:  3 * time.Minute,
    ViewChangeResendInterval:  5 * time.Second,
    ViewChangeTimeout:         20 * time.Second,
    LeaderHeartbeatTimeout:    time.Minute,
    LeaderHeartbeatCount:      10,
    CollectTimeout:            2 * time.Second,
}

We need to be able to set these to different values when starting an orderer. Most (if not all) of these need to be consistent across the cluster.

We'll add these to the Options field of  ConfigMetadata, in smartbft.configuration.proto. 

// Options to be specified for all the smartbft nodes. These can be modified on a
// per-channel basis.
type Options struct { ... }

At this point, it is recommended that configuration changes after start are made in maintenance mode, and require a restart, since the library itself does not support dynamic reconfiguration.

In addition, write an integration test that changes all of these.

**Comment by tock-ibm** [comment]
The WALDir is settable from the orderer.yaml and is retrieved just like in etcd/raft, no need to make changes there.
